# Generated by Django 4.0.3 on 2022-03-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '__first__'),
        ('core', '0002_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
