# Generated by Django 4.0.3 on 2022-03-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('atracoes', '__first__'),
        ('core', '0004_alter_pontoturistico_atracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
