# Generated by Django 4.0.3 on 2022-03-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pontoturistico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
