# Generated by Django 4.0.3 on 2022-03-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='nomes',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
