# Generated by Django 4.0.3 on 2022-03-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_atracao_nomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='atracao',
            name='nomes',
        ),
    ]
